### PR TITLE
5 merge nodepath and channel name

### PR DESCRIPTION
**Pull request by jacobson3**
Issues #5 and #6

### CODE REVIEW

**Comment by pollockm** [comment]
@jacobson3  - If you make a new branch on the OPC-UA repo and commit your local changes to that branch on the server, this will trigger an automatic build of the package and run all unit tests.  It looks like you made a fork on your personal account and merged from there.  If you don't have permissions to make a branch on this repo, let me know and we can fix it.

**Comment by pollockm** [comment]
(we should not approve pull requests unless we can see that they build and pass tests, which is triggered by the server)

**Comment by jacobson3** [comment]
@pollockm It does not look like I have the ability to make a new branch on this repo. Let me know when I get that ability and I can make the same changes in a new branch.

**Comment by pollockm** [comment]
Done.  You should have an email inviting you to the group.

**Comment by jacobson3** [comment]
Closing pull request. Issues are being addressed on separate branch.

**Pull request closed without merging**
